### ISSUE TITLE
可否提供详细的部署教程

### ISSUE THREAD

**Issue by zysord** [yangrds/WEB-OSS-Browser#1]
小白不会部署，可否出个详细教程，使用npm和yarn构建总是部署失败。🙏🙏

**Comment by yangrds** [comment]
> 小白不会部署，可否出详细教程，使用npm和yarn结构总是部署失败。🙏🙏

之前node-sass 指定了版本，导致和node版本不匹配，下载node-sass依赖的时候会一直失败，我已经重新更新了package.json，你在拉取重新下载依赖试试
如果还不行就，删除package.json的node-sass，然后yarn/npm install , 在yarn add node-sass -D
你试试看吧，不行的话继续反馈！！node-sass有时候因网络问题是比较难下载。

**Comment by zysord** [comment]
好的，感谢
